language: node_js
node_js:
  - '0.12.5'
before_script:
  - 'export CHROME_BIN=chromium-browser'
  - 'export DISPLAY=:99.0'
  - 'sh -e /etc/init.d/xvfb start'
  - 'npm install -g gulp phantomjs'
  - 'npm install' # install npm packages
  - 'npm run updateWebBrowser' # install npm packages
  - 'npm uninstall gulp-sass' # install npm packages
  - 'npm install gulp-sass' # install npm packages

after_script:
  - 'gulp connect & npm run e2e' # or other command for build, run tests, etc
